version: '3.8'
services:
  app:
    build: ./data_collection
    depends_on:
      - mongo
  mongo:
    image: mongo
    volumes:
      - mongodb_data:/data/db
  etl:
    build: ./etl
    depends_on:
      - mongo
      - mysql
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: weather
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
  metabase:
    image: metabase/metabase
    ports:
      - "3000:3000"
    depends_on:
      - mysql

volumes:
  mongodb_data:
  mysql_data:
