apiVersion: apps/v1
kind: Deployment
metadata:
  name: sgm-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sgm
  template:
    metadata:
      labels:
        app: sgm  # Corrected indentation here
    spec:
      containers:
      - name: mongodb
        image: europe-west3-docker.pkg.dev/quests-michael/sgm/mongo
        ports:
        - containerPort: 27017
      - name: mysql
        image: europe-west3-docker.pkg.dev/quests-michael/sgm/mysql
        ports:
        - containerPort: 3306
      - name: data-collection
        image: europe-west3-docker.pkg.dev/quests-michael/sgm/data_collection
      - name: etl
        image: europe-west3-docker.pkg.dev/quests-michael/sgm/etl
      - name: metabase
        image: europe-west3-docker.pkg.dev/quests-michael/sgm/metabase
        ports:
        - containerPort: 3000
